# Generated by Django 4.1.5 on 2023-02-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='intro',
        ),
    ]
